# Generated by Django 2.0.6 on 2018-07-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=150, verbose_name='Logradouro'),
        ),
    ]
