# Generated by Django 2.0.6 on 2018-08-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180801_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='endereco',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.Endereco'),
        ),
    ]
