# Generated by Django 2.0.6 on 2018-07-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180703_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=True, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
